--UNIQUE CONSTRAINTS
ALTER TABLE COMANDA ADD CONSTRAINT unique_id_client UNIQUE (id_client);
ALTER TABLE COMANDA ADD CONSTRAINT unique_id_vanzator UNIQUE (id_vanzator);
ALTER TABLE COMANDA ADD CONSTRAINT unique_id_transportator UNIQUE (id_transportator);

ALTER TABLE PRODUS ADD CONSTRAINT unique_id_comanda UNIQUE (id_comanda);
ALTER TABLE PRODUS ADD CONSTRAINT unique_id_depozit UNIQUE (id_depozit);

ALTER TABLE DEPOZIT ADD CONSTRAINT unique_id_vanzator2 UNIQUE (id_vanzator);

--RELATIONSHIP CONSTRAINTS
ALTER TABLE UTILIZATOR ADD FOREIGN KEY (id_utilizator) REFERENCES TRANSPORTATOR (id_transportator) MATCH SIMPLE;

ALTER TABLE UTILIZATOR ADD FOREIGN KEY (id_utilizator) REFERENCES CLIENT (id_client) MATCH SIMPLE;

ALTER TABLE UTILIZATOR ADD FOREIGN KEY (id_utilizator) REFERENCES VANZATOR (id_vanzator) MATCH SIMPLE;